name: Add PRs to the nRF Guide project

on:
  pull_request:
    types: opened

jobs:
  assign_to_project:
    runs-on: ubuntu-22.04
    steps:
      - name: Add to project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/bifravst/projects/2/views/1
          github-token: ${{ secrets.AUTO_ASSIGN_ISSUE_TOKEN }}
